export const CASHFLOW_CREATE_REQUEST = "CASHFLOW_CREATE_REQUEST";
export const CASHFLOW_CREATE_SUCCESS = "CASHFLOW_CREATE_SUCCESS";
export const CASHFLOW_CREATE_FAIL = "CASHFLOW_CREATE_FAIL";

export const CASHFLOW_LIST_MY_REQUEST = "CASHFLOW_LIST_MY_REQUEST";
export const CASHFLOW_LIST_MY_SUCCESS = "CASHFLOW_LIST_MY_SUCCESS";
export const CASHFLOW_LIST_MY_FAIL = "CASHFLOW_LIST_MY_FAIL";

export const CASHFLOW_MONEY_REQUEST = "CASHFLOW_MONEY_REQUEST";
export const CASHFLOW_MONEY_SUCCESS = "CASHFLOW_MONEY_SUCCESS";
export const CASHFLOW_MONEY_FAIL = "CASHFLOW_MONEY_FAIL";
