export const WALLET_CREATE_REQUEST = "WALLET_CREATE_REQUEST";
export const WALLET_CREATE_SUCCESS = "WALLET_CREATE_SUCCESS";
export const WALLET_CREATE_FAIL = "WALLET_CREATE_FAIL";


export const WALLET_UPDATE_REQUEST = "WALLET_UPDATE_REQUEST";
export const WALLET_UPDATE_SUCCESS = "WALLET_UPDATE_SUCCESS";
export const WALLET_UPDATE_FAIL = "WALLET_UPDATE_FAIL";